### ISSUE TITLE
Verifing the proof takes too much time

### ISSUE THREAD

**Issue by sdaveas** [sdaveas/popow#4]
Possible reasons: 
* implementation of EVM is slow
* ~proof is too big~

Edit:
proof of 45.000 and 450.000 blocks takes around the same time

**Comment by sdaveas** [comment]
Previous implementation used py-ethereum which had its own implementation of EVM.
Up-to-date EVMs (Py-EVM, ganache, geth) are considerably slower.

**Comment by sdaveas** [comment]
Maybe we will have to live with it. Use the EVM on regular bases for small proofs (100 Blocks = ~3 seconds) and test the big ones occasionally.

**Comment by sdaveas** [comment]
See the following links

https://github.com/ethereum/py-evm/issues/1904

https://docs.google.com/spreadsheets/d/1TQ72s-jjtWEoPOyhBJ6EvwE1l0Z5XfVUbfBnq1rh3ow/edit?usp=drivesdk

**Comment by dionyziz** [comment]
So this means a full proof will take 4 hours+ to verify?

**Comment by sdaveas** [comment]
With the correct configuration, 'geth' is fast enough (2.5 sec to submit a proof of 500K sized blockchain)
See https://github.com/sdaveas/setup-geth
